# Generated by Django 4.2.7 on 2024-06-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('plate_id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=10)),
                ('plate_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plate_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_address', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=50)),
                ('user_credit', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('violation_id', models.AutoField(primary_key=True, serialize=False)),
                ('violation_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_status', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.user')),
                ('vehicle_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.plate')),
            ],
        ),
        migrations.CreateModel(
            name='Trafficviolations',
            fields=[
                ('Trafficviolations_id', models.AutoField(primary_key=True, serialize=False)),
                ('violation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('violation_level', models.IntegerField()),
                ('email_status', models.BooleanField(default=False, null=True)),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.record')),
                ('violation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.violationtype')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle'),
        ),
    ]
