# Generated by Django 4.2.7 on 2024-06-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('emergency_id', models.AutoField(primary_key=True, serialize=False)),
                ('emergency_type', models.CharField(max_length=10)),
            ],
        ),
    ]
